name: Run tests.
on: [push]

jobs:
  build_and_test:
    name: Build and test lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
